### ISSUE TITLE
A bug?

### ISSUE THREAD

**Issue by ThinkLoudly** [lukebatchelor/css-tic-tac-toe#1]
Cool concept and thanks for the write up.

I just played a game with AI, Red should be the winner but it says it's draw.

`game g2 g3 g5 g9 r1 r4 r6 r7 r8 winner-d`

<img width="454" alt="default" src="https://user-images.githubusercontent.com/6403177/44336983-111a5c00-a471-11e8-8daf-22173fde79e6.PNG">

**Comment by lukebatchelor** [comment]
Oh interesting, I know exactly what caused it. I added a check that assumed that the last move would never cause a win. 

Looks like that was a bad assumption!

Thanks for spotting. Will clean up!

**Comment by lukebatchelor** [comment]
Also helped me spot a bad assumption in the `getComputerMove` code to.

:S.

Thanks again. :D
